// Package store is Runpool's durable state: which bindings exist, which
// work has been accepted, which leases are in flight and which Docker
// objects each one owns. The provider stays the remote demand authority
// and Docker inspection stays the execution observation; this package
// records intent and progress so a restarted controller can adopt or
// clean what it finds. It never holds secrets or raw JIT payloads.
//
// SQL lives only here. Most statements are generated by sqlc from files
// under query/, which humans wrote and reviewed; the lease and resource
// lifecycle keeps hand-written SQL because its compare-and-swap writes
// classify every outcome, and a generated wrapper would hide the
// difference between "no row matched" and "nothing to do". Both run on
// the same *sql.Tx, so a lifecycle transition and its bookkeeping commit
// or roll back together.
//
// The migrations are the single schema authority. The generated code
// compiles against a mechanical projection of them (schema/current.sql),
// and a parity test fails when the projection drifts.
package store

import (
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/rhobuild/runpool/internal/store/sqlitedb"

	_ "modernc.org/sqlite"
)

// dsn is the connection contract the durability suite in
// test/contract/sqlite qualifies (see
// docs/adrs/2026-08-11-sqlite-driver.md): WAL with synchronous=FULL so a
// committed transition survives abrupt termination, enforced foreign
// keys, immediate transactions, and a shared busy timeout.
func dsn(path string) string {
	return "file:" + path +
		"?_txlock=immediate" +
		"&_pragma=journal_mode(wal)" +
		"&_pragma=synchronous(full)" +
		"&_pragma=foreign_keys(1)" +
		"&_pragma=busy_timeout(10000)"
}

// DatabaseFile is the database's name inside the state directory.
const DatabaseFile = "runpool.db"

type Store struct {
	db         *sql.DB
	dir        string
	instanceID string
	// readOnly stores opened for reporting take deferred transactions, so
	// they neither acquire a write lock nor block a live controller.
	readOnly bool
	// retryBudget is how many times one attempt may be leased before it is
	// held for review. Read by transactions, set once at open.
	retryBudget int
}

// readOnlyDSN opens an existing database for reading only. mode=ro makes
// the driver refuse to create the file, query_only makes writes fail at
// the engine, and no journal pragma is set because setting one is itself
// a write — which is how a reporting command once created a database it
// was only supposed to read.
func readOnlyDSN(path string) string {
	return "file:" + path +
		"?mode=ro" +
		"&_pragma=query_only(1)" +
		"&_pragma=foreign_keys(1)" +
		"&_pragma=busy_timeout(5000)"
}

// ErrNoState reports that a state directory holds no database yet.
var ErrNoState = errors.New("no state database in this directory")

// ErrSchemaBehind reports a database the controller has not migrated yet.
// It is named so a command whose applying form would migrate can say so:
// the refusal is about this command, not about the instance.
var ErrSchemaBehind = errors.New("state schema predates this build")

// OpenReadOnly opens an existing database for reporting. It applies no
// migrations, creates nothing, and cannot write: a status command must
// leave a store a live controller owns byte-for-byte unchanged.
func OpenReadOnly(dir string) (*Store, error) {
	path := filepath.Join(dir, DatabaseFile)
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, ErrNoState
		}
		return nil, err
	}
	db, err := sql.Open("sqlite", readOnlyDSN(path))
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1)
	s := &Store{db: db, dir: dir, readOnly: true, retryBudget: DefaultRetryBudget}
	if err := s.checkSchemaReadable(); err != nil {
		db.Close()
		return nil, err
	}
	if err := s.loadIdentityReadOnly(); err != nil {
		db.Close()
		return nil, err
	}
	return s, nil
}

// checkSchemaReadable refuses a database this build cannot report on.
//
// A reporting command applies no migrations, so it has to answer for the
// schema it finds. Every direction is reachable in ordinary use and each
// produces a raw "no such table" from the first query that meets it: a
// newer schema after a downgrade, an older one in the window between
// installing a build and restarting the controller that would migrate it,
// and — while the baseline is still mutable — one whose version matches
// and whose contents do not.
func (s *Store) checkSchemaReadable() error {
	migrations, err := loadMigrations()
	if err != nil {
		return err
	}
	current, err := s.SchemaVersion()
	if err != nil {
		return err
	}
	switch {
	case current > len(migrations):
		return newerSchemaError(current, len(migrations), s.dir)
	case current < len(migrations):
		return fmt.Errorf("%w: version %d, and this build expects %d.\n"+
			"A reporting command migrates nothing.\n"+
			"  - start the controller to migrate it, which takes a backup first, then run this again",
			ErrSchemaBehind, current, len(migrations))
	}
	return s.verifyFingerprint(migrations)
}

func (s *Store) loadIdentityReadOnly() error {
	return s.db.QueryRow(`SELECT v FROM meta WHERE k = 'instance_id'`).Scan(&s.instanceID)
}

// Option adjusts a store at open time. Options exist for the values a
// deployment configures; everything else about a store is a property of
// the schema and is not adjustable.
type Option func(*Store)

// WithRetryBudget sets how many times one attempt may be leased before it
// is held for review. A count below one is ignored: it would not be a
// smaller budget but no budget at all, reopening the unbounded retry the
// counter exists to close. What a deployment may legitimately set is a
// configuration rule, checked by the validator; a store opened by a
// maintenance command has no configuration to read and keeps the default.
func WithRetryBudget(n int) Option {
	return func(s *Store) {
		if n >= 1 {
			s.retryBudget = n
		}
	}
}

// Open opens (creating if needed) the database in the state directory,
// applies pending migrations, and loads the stable instance identity.
func Open(dir string, opts ...Option) (*Store, error) {
	db, err := sql.Open("sqlite", dsn(filepath.Join(dir, DatabaseFile)))
	if err != nil {
		return nil, err
	}
	// The store is a single writer; concurrency control across processes
	// is the flock in this same directory, not connection pooling.
	db.SetMaxOpenConns(1)

	s := &Store{db: db, dir: dir, retryBudget: DefaultRetryBudget}
	for _, opt := range opts {
		opt(s)
	}
	migrations, err := loadMigrations()
	if err == nil {
		err = s.applyMigrations(migrations)
	}
	if err == nil {
		err = s.loadIdentity()
	}
	if err != nil {
		db.Close()
		return nil, err
	}
	return s, nil
}

func (s *Store) Close() error { return s.db.Close() }

// InstanceID is the stable opaque identity stamped on every owned Docker
// resource (io.runpool.instance); it is generated once per state volume.
func (s *Store) InstanceID() string { return s.instanceID }

// SchemaVersion exposes the migration level for diagnostics.
func (s *Store) SchemaVersion() (int, error) {
	var v int
	err := s.db.QueryRow(`PRAGMA user_version`).Scan(&v)
	return v, err
}

// Backup writes a consistent online snapshot to path using VACUUM INTO,
// the mechanism the durability suite qualifies; it fails if path already
// exists.
func (s *Store) Backup(ctx context.Context, path string) error {
	quoted := strings.ReplaceAll(path, "'", "''")
	if _, err := s.db.ExecContext(ctx, `VACUUM INTO '`+quoted+`'`); err != nil {
		return fmt.Errorf("backup to %s: %w", path, err)
	}
	return nil
}

// Tx is one transaction over the store. Every query in the package hangs
// off it — hand-written through tx, generated through q — so a caller
// cannot accidentally split one logical change across two transactions.
type Tx struct {
	ctx context.Context
	tx  *sql.Tx
	q   *sqlitedb.Queries
	// s is the store this transaction belongs to, for the values it was
	// opened with. Not for reaching back into the database: a transaction
	// that took a second connection would deadlock against its own.
	s *Store
}

// Tx runs fn inside one transaction: immediate for a writable store, so
// every lifecycle transition and its bookkeeping commit or roll back
// together; read-only for a reporting store, which must not take a write
// lock the controller needs.
func (s *Store) Tx(ctx context.Context, fn func(*Tx) error) error {
	tx, err := s.db.BeginTx(ctx, &sql.TxOptions{ReadOnly: s.readOnly})
	if err != nil {
		return err
	}
	// The deferred rollback covers the path an explicit one cannot: a panic
	// inside fn. The pool is one connection, so a transaction left open
	// checks it out for the life of the process and every later query
	// blocks on it. Rollback after a successful Commit is a no-op.
	defer func() { _ = tx.Rollback() }()
	if err := fn(&Tx{ctx: ctx, tx: tx, q: sqlitedb.New(tx), s: s}); err != nil {
		return err
	}
	return tx.Commit()
}

func (s *Store) loadIdentity() error {
	return s.Tx(context.Background(), func(tx *Tx) error {
		id, err := tx.metaGet("instance_id")
		if err != nil {
			return err
		}
		if id == "" {
			id = newID(16)
			if err := tx.metaSet("instance_id", id); err != nil {
				return err
			}
		}
		s.instanceID = id
		return nil
	})
}

// newID returns n random bytes as lowercase hex — the opaque identifier
// form used for instances, leases and cache lanes.
func newID(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic(err) // the platform CSPRNG failing is not a recoverable state
	}
	return hex.EncodeToString(b)
}

func (t *Tx) metaGet(key string) (string, error) {
	var v string
	err := t.tx.QueryRow(`SELECT v FROM meta WHERE k = ?`, key).Scan(&v)
	if errors.Is(err, sql.ErrNoRows) {
		return "", nil
	}
	return v, err
}

func (t *Tx) metaSet(key, value string) error {
	_, err := t.tx.Exec(
		`INSERT INTO meta (k, v) VALUES (?, ?) ON CONFLICT (k) DO UPDATE SET v = excluded.v`,
		key, value)
	return err
}

// mustAffect turns a compare-and-swap that matched no row into
// ErrNotFound. A silent no-op is the one outcome these writes must never
// produce: the caller would believe something was recorded.
func (t *Tx) mustAffect(res sql.Result, err error) error {
	if err != nil {
		return err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}
