// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempt_events.sql

package sqlitedb

import (
	"context"
)

const insertAttemptEvent = `-- name: InsertAttemptEvent :execrows

INSERT INTO attempt_events (attempt_id, idempotency_key, kind, detail_json)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (attempt_id, idempotency_key) DO NOTHING
`

type InsertAttemptEventParams struct {
	AttemptID      string
	IdempotencyKey string
	Kind           string
	DetailJSON     string
}

// Attempt lifecycle events: append-only, idempotent per
// (attempt, idempotency key), so a redelivered message cannot double
// history. Zero rows from an insert means the event already exists under
// that key, which the repository reports as success: the key is what
// makes two writes the same event, so nothing is read back to confirm
// it.
// For a decision that happens at most once per attempt, or one whose key
// already carries what makes it distinct -- a lease id, a delivery id.
func (q *Queries) InsertAttemptEvent(ctx context.Context, arg InsertAttemptEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAttemptEvent,
		arg.AttemptID,
		arg.IdempotencyKey,
		arg.Kind,
		arg.DetailJSON,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertSequencedAttemptEvent = `-- name: InsertSequencedAttemptEvent :execrows
INSERT INTO attempt_events (attempt_id, idempotency_key, kind, detail_json)
SELECT ?1,
       ?2 || ':' || (SELECT count(*) FROM attempt_events prior
                        WHERE prior.attempt_id = ?1 AND prior.kind = ?2),
       ?2, ?3
`

type InsertSequencedAttemptEventParams struct {
	AttemptID  string
	Kind       string
	DetailJSON string
}

// For a decision that can be made about one attempt more than once: held
// for review, resolved by an operator, served again, held again.
//
// A fixed key makes every occurrence after the first a replay of it, and
// the conflict clause then drops the actor, the reason and the decision
// without a word. The attempt row keeps only the latest of each, so what
// is lost is precisely the history -- who decided what, and why, the
// time before.
//
// The key carries how many of this kind the attempt already has.
//
// What the conflict clause on the insert above protects against is a
// redelivered message: those events key by delivery id, which is the
// identity the outside world repeats. A hold or a resolve has no such
// identity. The command runs once, and a second run finds the
// compare-and-swap refusing, so a fixed key protected against nothing
// while dropping every later decision to do it.
//
// This one carries no such clause, because it has no reachable conflict.
// The count only grows: the sole delete of these rows drops the attempts
// with them, and a row written under the old fixed key shifts the
// numbering without ever occupying a suffixed one. Two writes inside one
// transaction do not collide either, because SQLite shows an uncommitted
// insert to the statements after it, so the second counts the first and
// takes the next number.
//
// Leaving the clause on would mean that a duplicate nobody can construct
// would be dropped in silence, with no error, from an append-only audit
// log. If one is ever constructed, saying so is the only useful answer.
func (q *Queries) InsertSequencedAttemptEvent(ctx context.Context, arg InsertSequencedAttemptEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSequencedAttemptEvent, arg.AttemptID, arg.Kind, arg.DetailJSON)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAttemptEvents = `-- name: ListAttemptEvents :many
SELECT id, attempt_id, idempotency_key, kind, detail_json, created_at
FROM attempt_events
WHERE attempt_id = ?1
ORDER BY id
`

func (q *Queries) ListAttemptEvents(ctx context.Context, attemptID string) ([]AttemptEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptEvents, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptEvent{}
	for rows.Next() {
		var i AttemptEvent
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.IdempotencyKey,
			&i.Kind,
			&i.DetailJSON,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
