// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempt_events.sql

package sqlitedb

import (
	"context"
)

const getAttemptEventByKey = `-- name: GetAttemptEventByKey :one
SELECT id, attempt_id, idempotency_key, kind, detail_json, created_at
FROM attempt_events
WHERE attempt_id = ?1
  AND idempotency_key = ?2
`

type GetAttemptEventByKeyParams struct {
	AttemptID      string
	IdempotencyKey string
}

func (q *Queries) GetAttemptEventByKey(ctx context.Context, arg GetAttemptEventByKeyParams) (AttemptEvent, error) {
	row := q.db.QueryRowContext(ctx, getAttemptEventByKey, arg.AttemptID, arg.IdempotencyKey)
	var i AttemptEvent
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.DetailJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttemptEvent = `-- name: InsertAttemptEvent :execrows

INSERT INTO attempt_events (attempt_id, idempotency_key, kind, detail_json)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (attempt_id, idempotency_key) DO NOTHING
`

type InsertAttemptEventParams struct {
	AttemptID      string
	IdempotencyKey string
	Kind           string
	DetailJson     string
}

// Attempt lifecycle events: append-only, idempotent per
// (attempt, idempotency key), so a redelivered message cannot double
// history. Zero rows from the insert means the event already exists,
// which the repository reports as idempotent success after verifying
// the existing event matches.
func (q *Queries) InsertAttemptEvent(ctx context.Context, arg InsertAttemptEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAttemptEvent,
		arg.AttemptID,
		arg.IdempotencyKey,
		arg.Kind,
		arg.DetailJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAttemptEvents = `-- name: ListAttemptEvents :many
SELECT id, attempt_id, idempotency_key, kind, detail_json, created_at
FROM attempt_events
WHERE attempt_id = ?1
ORDER BY id
`

func (q *Queries) ListAttemptEvents(ctx context.Context, attemptID string) ([]AttemptEvent, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptEvents, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttemptEvent{}
	for rows.Next() {
		var i AttemptEvent
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.IdempotencyKey,
			&i.Kind,
			&i.DetailJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
