// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package sqlitedb

import (
	"context"
)

const authorizeAttemptStart = `-- name: AuthorizeAttemptStart :execrows
UPDATE assignment_attempts
SET state = 'starting'
WHERE assignment_attempts.id = ?1
  AND assignment_attempts.state IN ('leased', 'preparing', 'prepared')
  AND EXISTS (SELECT 1 FROM capsule_leases
              WHERE capsule_leases.id = ?2
                AND capsule_leases.attempt_id = ?1
                AND capsule_leases.state <> 'released')
`

type AuthorizeAttemptStartParams struct {
	AttemptID string
	LeaseID   string
}

// The one authoritative edge in the walk, and the reason it names a set
// rather than a single state.
//
// Every other edge is best-effort observability, written outside the
// transaction that matters and logged rather than retried when it fails.
// So a serving that reached a prepared capsule may still have its attempt
// sitting at any state it passed through, and requiring the last of them
// turns one lost observability write into a torn-down capsule and a
// burnt serving.
//
// What must not match is an attempt somebody else resolved. superseded,
// canceled, settled and manual_review are all outside this set, so a
// redelivery that replaced this attempt during preparation still stops
// the start, which is the property the edge exists for.
//
// The set alone does not say the attempt is still this serving's, only
// that nobody has resolved it. `prepared` used to carry that by
// accident, being a marker the starting goroutine had just written
// itself; `leased` is written by whoever claimed the attempt. So the
// lease is named here too, and at-most-once is proved by the row rather
// than by an in-memory claim and two partial indexes agreeing.
func (q *Queries) AuthorizeAttemptStart(ctx context.Context, arg AuthorizeAttemptStartParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, authorizeAttemptStart, arg.AttemptID, arg.LeaseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelReadyAttempt = `-- name: CancelReadyAttempt :execrows
UPDATE assignment_attempts
SET state = 'canceled', resolution = ?1, settled_at = unixepoch()
WHERE id = ?2 AND state = 'ready'
`

type CancelReadyAttemptParams struct {
	Resolution string
	AttemptID  string
}

// A remote cancellation may close an attempt that is not yet executing;
// anything past ready is running work, whose cancellation is a drain
// concern, not a row update.
func (q *Queries) CancelReadyAttempt(ctx context.Context, arg CancelReadyAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelReadyAttempt, arg.Resolution, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimReadyAttempt = `-- name: ClaimReadyAttempt :execrows
UPDATE assignment_attempts
SET state = 'leased'
WHERE id = ?1 AND state = 'ready'
`

// Claiming is the compare-and-swap that decides who serves a workload:
// exactly one caller moves it out of ready, and the lease row committed
// alongside it in the same transaction carries the link back.
func (q *Queries) ClaimReadyAttempt(ctx context.Context, attemptID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimReadyAttempt, attemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countReadyAttempts = `-- name: CountReadyAttempts :one
SELECT COUNT(*) FROM assignment_attempts
WHERE binding_id = ?1 AND state = 'ready'
`

// The depth of a binding's queue. A ready attempt is served in age order
// as soon as a lane frees, so a count that stays high is the operator's
// signal that no lane is freeing.
func (q *Queries) CountReadyAttempts(ctx context.Context, bindingID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReadyAttempts, bindingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, delivery_id, binding_id, source_workload_key, tenant_key, project_key,
       state, execution_evidence, resolution, review_reason, reviewed_at,
       reviewed_by, received_at, settled_at
FROM assignment_attempts
WHERE id = ?1
`

func (q *Queries) GetAttempt(ctx context.Context, id string) (AssignmentAttempt, error) {
	row := q.db.QueryRowContext(ctx, getAttempt, id)
	var i AssignmentAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.BindingID,
		&i.SourceWorkloadKey,
		&i.TenantKey,
		&i.ProjectKey,
		&i.State,
		&i.ExecutionEvidence,
		&i.Resolution,
		&i.ReviewReason,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReceivedAt,
		&i.SettledAt,
	)
	return i, err
}

const getAttemptByLease = `-- name: GetAttemptByLease :one
SELECT a.id, a.delivery_id, a.binding_id, a.source_workload_key, a.tenant_key,
       a.project_key, a.state, a.execution_evidence, a.resolution,
       a.review_reason, a.reviewed_at, a.reviewed_by, a.received_at, a.settled_at
FROM assignment_attempts a
JOIN capsule_leases l ON l.attempt_id = a.id
WHERE l.id = ?1
`

func (q *Queries) GetAttemptByLease(ctx context.Context, leaseID string) (AssignmentAttempt, error) {
	row := q.db.QueryRowContext(ctx, getAttemptByLease, leaseID)
	var i AssignmentAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.BindingID,
		&i.SourceWorkloadKey,
		&i.TenantKey,
		&i.ProjectKey,
		&i.State,
		&i.ExecutionEvidence,
		&i.Resolution,
		&i.ReviewReason,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReceivedAt,
		&i.SettledAt,
	)
	return i, err
}

const getOpenAttemptByWorkload = `-- name: GetOpenAttemptByWorkload :one
SELECT id, delivery_id, binding_id, source_workload_key, tenant_key, project_key,
       state, execution_evidence, resolution, review_reason, reviewed_at,
       reviewed_by, received_at, settled_at
FROM assignment_attempts
WHERE binding_id = ?1
  AND source_workload_key = ?2
  AND state IN ('ready', 'leased', 'preparing', 'prepared',
                'starting', 'running', 'manual_review')
`

type GetOpenAttemptByWorkloadParams struct {
	BindingID         int64
	SourceWorkloadKey string
}

func (q *Queries) GetOpenAttemptByWorkload(ctx context.Context, arg GetOpenAttemptByWorkloadParams) (AssignmentAttempt, error) {
	row := q.db.QueryRowContext(ctx, getOpenAttemptByWorkload, arg.BindingID, arg.SourceWorkloadKey)
	var i AssignmentAttempt
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.BindingID,
		&i.SourceWorkloadKey,
		&i.TenantKey,
		&i.ProjectKey,
		&i.State,
		&i.ExecutionEvidence,
		&i.Resolution,
		&i.ReviewReason,
		&i.ReviewedAt,
		&i.ReviewedBy,
		&i.ReceivedAt,
		&i.SettledAt,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :execrows

INSERT INTO assignment_attempts
	(id, delivery_id, binding_id, source_workload_key, tenant_key, project_key)
VALUES
	(?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (delivery_id, source_workload_key) DO NOTHING
`

type InsertAttemptParams struct {
	ID                string
	DeliveryID        int64
	BindingID         int64
	SourceWorkloadKey string
	TenantKey         string
	ProjectKey        string
}

// Assignment attempts: the local execution lifecycle of one workload
// under one delivery, and the sole owner of what was observed about it.
// Every state change is compare-and-swap: zero rows affected means the
// row moved, and the caller re-reads instead of forcing the write. ASCII
// only in these files - sqlc v1.31.1's sqlite lexer loses the comment
// boundary on multibyte characters and reports phantom parse errors
// several statements later.
//
// Nothing here names a lease. The link lives on capsule_leases, so
// purging a finished lease takes the link with it and no settled attempt
// can pin a runtime row forever.
func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertAttempt,
		arg.ID,
		arg.DeliveryID,
		arg.BindingID,
		arg.SourceWorkloadKey,
		arg.TenantKey,
		arg.ProjectKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAttemptsByDelivery = `-- name: ListAttemptsByDelivery :many
SELECT id, delivery_id, binding_id, source_workload_key, tenant_key, project_key,
       state, execution_evidence, resolution, review_reason, reviewed_at,
       reviewed_by, received_at, settled_at
FROM assignment_attempts
WHERE delivery_id = ?1
ORDER BY received_at, id
`

func (q *Queries) ListAttemptsByDelivery(ctx context.Context, deliveryID int64) ([]AssignmentAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listAttemptsByDelivery, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentAttempt{}
	for rows.Next() {
		var i AssignmentAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.BindingID,
			&i.SourceWorkloadKey,
			&i.TenantKey,
			&i.ProjectKey,
			&i.State,
			&i.ExecutionEvidence,
			&i.Resolution,
			&i.ReviewReason,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReceivedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualReviewAttempts = `-- name: ListManualReviewAttempts :many
SELECT id, delivery_id, binding_id, source_workload_key, tenant_key, project_key,
       state, execution_evidence, resolution, review_reason, reviewed_at,
       reviewed_by, received_at, settled_at
FROM assignment_attempts
WHERE state = 'manual_review'
ORDER BY received_at, id
`

func (q *Queries) ListManualReviewAttempts(ctx context.Context) ([]AssignmentAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listManualReviewAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentAttempt{}
	for rows.Next() {
		var i AssignmentAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.BindingID,
			&i.SourceWorkloadKey,
			&i.TenantKey,
			&i.ProjectKey,
			&i.State,
			&i.ExecutionEvidence,
			&i.Resolution,
			&i.ReviewReason,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReceivedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyAttempts = `-- name: ListReadyAttempts :many
SELECT id, delivery_id, binding_id, source_workload_key, tenant_key, project_key,
       state, execution_evidence, resolution, review_reason, reviewed_at,
       reviewed_by, received_at, settled_at
FROM assignment_attempts
WHERE binding_id = ?1 AND state = 'ready'
ORDER BY received_at, id
`

func (q *Queries) ListReadyAttempts(ctx context.Context, bindingID int64) ([]AssignmentAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listReadyAttempts, bindingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentAttempt{}
	for rows.Next() {
		var i AssignmentAttempt
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.BindingID,
			&i.SourceWorkloadKey,
			&i.TenantKey,
			&i.ProjectKey,
			&i.State,
			&i.ExecutionEvidence,
			&i.Resolution,
			&i.ReviewReason,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.ReceivedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAttemptManualReview = `-- name: MarkAttemptManualReview :execrows
UPDATE assignment_attempts
SET state = 'manual_review', review_reason = ?1
WHERE id = ?2
  AND state IN ('ready', 'leased', 'preparing', 'prepared', 'starting', 'running')
`

type MarkAttemptManualReviewParams struct {
	ReviewReason string
	AttemptID    string
}

func (q *Queries) MarkAttemptManualReview(ctx context.Context, arg MarkAttemptManualReviewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAttemptManualReview, arg.ReviewReason, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordAttemptEvidence = `-- name: RecordAttemptEvidence :execrows
UPDATE assignment_attempts
SET execution_evidence = ?1
WHERE id = ?2 AND execution_evidence = ?3
`

type RecordAttemptEvidenceParams struct {
	Next      string
	AttemptID string
	Current   string
}

// Evidence is monotonic and compare-and-swap on the value the caller
// read. If another writer moved it in between, nothing is written and
// the caller re-reads: an observation that was made cannot be unmade by
// a slower writer.
func (q *Queries) RecordAttemptEvidence(ctx context.Context, arg RecordAttemptEvidenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordAttemptEvidence, arg.Next, arg.AttemptID, arg.Current)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueAttempt = `-- name: RequeueAttempt :execrows
UPDATE assignment_attempts
SET state = 'ready', execution_evidence = 'not_started'
WHERE id = ?1 AND state IN ('leased', 'preparing', 'prepared')
`

// Only stages that provably started nothing may return to ready:
// leased, preparing and prepared all precede the start authorization.
// From starting onward at-most-once rules, and requeue must refuse.
//
// The evidence resets like the proof-carrying requeue's does, and for the
// same reason: the serving is over and the next one starts from nothing,
// so an authorization left behind would make the next serving's first
// honest observation a write that moves backwards.
//
// Reaching here with that authorization already recorded is not possible
// as the code stands: the walk to starting is the authoritative edge and
// it commits before the evidence, so an attempt this guard accepts has
// not been authorized. The reset is what keeps that a property of the
// ordering rather than something this query depends on.
func (q *Queries) RequeueAttempt(ctx context.Context, attemptID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueAttempt, attemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requeueProvenInertAttempt = `-- name: RequeueProvenInertAttempt :execrows
UPDATE assignment_attempts
SET state = 'ready', execution_evidence = 'not_started'
WHERE id = ?1 AND state IN ('starting', 'running')
`

// The one legal requeue past the start authorization: the daemon proved
// the start never took effect (the runtime is still in its created
// state), so the at-most-once rule has nothing to protect.
//
// The evidence goes back with it. It is monotonic within one serving, and
// the proof this requeue carries is exactly what ends that serving: the
// capsule is destroyed and the next one starts from nothing, so leaving
// the authorization behind makes its first honest observation - the
// runtime being prepared - a write that moves backwards, and every retry
// of this shape ends in review after burning a lease. What each serving
// observed is kept in attempt_events either way.
//
// `running` is in the guard beside `starting` because the walk that
// advances an attempt is optimistic: it writes `running` when the start
// is authorized and the capsule reports itself up, which is before the
// wait that can prove the runner never took the job. The proof arrives
// with the attempt already past `starting`, and a guard naming only that
// state matches no row: the finalizing transaction then rolls back and
// the lease pins in cleaning holding its credit.
func (q *Queries) RequeueProvenInertAttempt(ctx context.Context, attemptID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueProvenInertAttempt, attemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveManualReviewToReady = `-- name: ResolveManualReviewToReady :execrows
UPDATE assignment_attempts
SET state = 'ready', execution_evidence = 'not_started', review_reason = '',
    resolution = ?1, reviewed_at = unixepoch(), reviewed_by = ?2
WHERE id = ?3 AND state = 'manual_review'
`

type ResolveManualReviewToReadyParams struct {
	Resolution string
	ReviewedBy string
	AttemptID  string
}

// An operator who resolves to ready has established what review could
// not, and that verdict ends the serving being reviewed. The evidence
// resets with it for the same reason RequeueProvenInertAttempt's does:
// the next serving starts from nothing, and what this one observed
// remains in attempt_events.
func (q *Queries) ResolveManualReviewToReady(ctx context.Context, arg ResolveManualReviewToReadyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveManualReviewToReady, arg.Resolution, arg.ReviewedBy, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveManualReviewToSettled = `-- name: ResolveManualReviewToSettled :execrows
UPDATE assignment_attempts
SET state = 'settled', resolution = ?1,
    reviewed_at = unixepoch(), reviewed_by = ?2,
    settled_at = unixepoch()
WHERE id = ?3 AND state = 'manual_review'
`

type ResolveManualReviewToSettledParams struct {
	Resolution string
	ReviewedBy string
	AttemptID  string
}

func (q *Queries) ResolveManualReviewToSettled(ctx context.Context, arg ResolveManualReviewToSettledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveManualReviewToSettled, arg.Resolution, arg.ReviewedBy, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const settleAttempt = `-- name: SettleAttempt :execrows
UPDATE assignment_attempts
SET state = 'settled', resolution = ?1, settled_at = unixepoch()
WHERE id = ?2 AND state = ?3
`

type SettleAttemptParams struct {
	Resolution string
	AttemptID  string
	Current    string
}

func (q *Queries) SettleAttempt(ctx context.Context, arg SettleAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, settleAttempt, arg.Resolution, arg.AttemptID, arg.Current)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const supersedeAttempt = `-- name: SupersedeAttempt :execrows
UPDATE assignment_attempts
SET state = 'superseded', resolution = ?1, settled_at = unixepoch()
WHERE id = ?2
  AND state IN ('ready', 'leased', 'preparing', 'prepared', 'manual_review')
  AND execution_evidence IN ('not_started', 'runtime_prepared')
`

type SupersedeAttemptParams struct {
	Resolution string
	AttemptID  string
}

// Every open state that provably consumed nothing, and no other.
//
// `starting` and `running` are absent and must stay absent: a start was
// authorized there, and replacing such an attempt is how one workload
// comes to run twice. A redelivery that meets one leaves its message
// unacknowledged and waits for the predecessor's own lifecycle to end
// it, which is the correct stall.
//
// `preparing` belongs here for the opposite reason - it precedes the
// authorization exactly as `leased` and `prepared` do - and leaving it
// out stalled a binding's whole ordered queue on an attempt that had
// consumed nothing.
//
// `manual_review` belongs here too. It is an open state, so an attempt
// held in it blocks every redelivery of that workload, and the provider
// reassigning the work is precisely what makes a pending human decision
// moot. The superseded resolution keeps the trail.
//
// But a review is reachable from `starting` and `running`, and
// `start_outcome_unknown` is exactly the review of an attempt whose
// start was authorized and whose outcome nobody could prove. Replacing
// that one is a second execution of work that may have run. So the
// evidence has to agree with the state: nothing beyond a prepared
// runtime was ever consumed. It also closes the same question for the
// pre-authorization states, none of which can be trusted to imply their
// own evidence forever.
func (q *Queries) SupersedeAttempt(ctx context.Context, arg SupersedeAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, supersedeAttempt, arg.Resolution, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const transitionAttempt = `-- name: TransitionAttempt :execrows
UPDATE assignment_attempts
SET state = ?1
WHERE id = ?2 AND state = ?3
`

type TransitionAttemptParams struct {
	Next      string
	AttemptID string
	Current   string
}

func (q *Queries) TransitionAttempt(ctx context.Context, arg TransitionAttemptParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionAttempt, arg.Next, arg.AttemptID, arg.Current)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
