// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bindings.sql

package sqlitedb

import (
	"context"
)

const getProviderBinding = `-- name: GetProviderBinding :one
SELECT id, target_id, provider_kind, source_binding_key, desired_state, created_at
FROM provider_bindings
WHERE provider_kind = ?1
  AND source_binding_key = ?2
`

type GetProviderBindingParams struct {
	ProviderKind     string
	SourceBindingKey string
}

func (q *Queries) GetProviderBinding(ctx context.Context, arg GetProviderBindingParams) (ProviderBinding, error) {
	row := q.db.QueryRowContext(ctx, getProviderBinding, arg.ProviderKind, arg.SourceBindingKey)
	var i ProviderBinding
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.ProviderKind,
		&i.SourceBindingKey,
		&i.DesiredState,
		&i.CreatedAt,
	)
	return i, err
}

const insertProviderBinding = `-- name: InsertProviderBinding :one

INSERT INTO provider_bindings (target_id, provider_kind, source_binding_key)
VALUES (?1, ?2, ?3)
ON CONFLICT (provider_kind, source_binding_key) DO UPDATE SET target_id = excluded.target_id
RETURNING id, target_id, provider_kind, source_binding_key, desired_state, created_at
`

type InsertProviderBindingParams struct {
	TargetID         string
	ProviderKind     string
	SourceBindingKey string
}

// Provider bindings: the neutral identity a delivery belongs to.
// Parameters are named (@x) throughout: positional arguments invite the
// column-order bugs this generation step exists to eliminate.
func (q *Queries) InsertProviderBinding(ctx context.Context, arg InsertProviderBindingParams) (ProviderBinding, error) {
	row := q.db.QueryRowContext(ctx, insertProviderBinding, arg.TargetID, arg.ProviderKind, arg.SourceBindingKey)
	var i ProviderBinding
	err := row.Scan(
		&i.ID,
		&i.TargetID,
		&i.ProviderKind,
		&i.SourceBindingKey,
		&i.DesiredState,
		&i.CreatedAt,
	)
	return i, err
}

const listProviderBindings = `-- name: ListProviderBindings :many
SELECT id, target_id, provider_kind, source_binding_key, desired_state, created_at
FROM provider_bindings
ORDER BY target_id, source_binding_key
`

func (q *Queries) ListProviderBindings(ctx context.Context) ([]ProviderBinding, error) {
	rows, err := q.db.QueryContext(ctx, listProviderBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderBinding{}
	for rows.Next() {
		var i ProviderBinding
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.ProviderKind,
			&i.SourceBindingKey,
			&i.DesiredState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderBindingsWithContact = `-- name: ListProviderBindingsWithContact :many
SELECT b.id, b.target_id, b.provider_kind, b.source_binding_key, b.desired_state, b.created_at,
       coalesce(c.last_contact_at_ms, 0) AS last_contact_at_ms,
       coalesce(c.last_error, '')        AS last_error,
       coalesce(c.last_error_at_ms, 0)   AS last_error_at_ms
FROM provider_bindings b
LEFT JOIN provider_binding_contact c ON c.binding_id = b.id
ORDER BY b.target_id, b.source_binding_key
`

type ListProviderBindingsWithContactRow struct {
	ID               int64
	TargetID         string
	ProviderKind     string
	SourceBindingKey string
	DesiredState     string
	CreatedAt        int64
	LastContactAtMs  int64
	LastError        string
	LastErrorAtMs    int64
}

// The reach travels with the binding in one query: a list plus a lookup
// joined in Go is two reads a write can straddle, and the join is the
// database's job. A binding that has never run reports zeroes, which is
// not the same as failing: the first has nothing to say, the second has
// a reason.
func (q *Queries) ListProviderBindingsWithContact(ctx context.Context) ([]ListProviderBindingsWithContactRow, error) {
	rows, err := q.db.QueryContext(ctx, listProviderBindingsWithContact)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderBindingsWithContactRow{}
	for rows.Next() {
		var i ListProviderBindingsWithContactRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetID,
			&i.ProviderKind,
			&i.SourceBindingKey,
			&i.DesiredState,
			&i.CreatedAt,
			&i.LastContactAtMs,
			&i.LastError,
			&i.LastErrorAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProviderContact = `-- name: RecordProviderContact :exec
INSERT INTO provider_binding_contact (binding_id, last_contact_at_ms, last_error, last_error_at_ms)
VALUES (?1, ?2, '', 0)
ON CONFLICT (binding_id) DO UPDATE
SET last_contact_at_ms = excluded.last_contact_at_ms, last_error = '', last_error_at_ms = 0
`

type RecordProviderContactParams struct {
	BindingID int64
	At        int64
}

// A success clears the failure: what is reported is the current state of
// the binding's reach, not a log of everything that ever went wrong.
func (q *Queries) RecordProviderContact(ctx context.Context, arg RecordProviderContactParams) error {
	_, err := q.db.ExecContext(ctx, recordProviderContact, arg.BindingID, arg.At)
	return err
}

const recordProviderFailure = `-- name: RecordProviderFailure :exec
INSERT INTO provider_binding_contact (binding_id, last_contact_at_ms, last_error, last_error_at_ms)
VALUES (?1, 0, ?2, ?3)
ON CONFLICT (binding_id) DO UPDATE
SET last_error = excluded.last_error, last_error_at_ms = excluded.last_error_at_ms
`

type RecordProviderFailureParams struct {
	BindingID int64
	LastError string
	At        int64
}

// The last contact is left alone: how long a binding has been unable to
// reach its provider is the question a failure raises.
func (q *Queries) RecordProviderFailure(ctx context.Context, arg RecordProviderFailureParams) error {
	_, err := q.db.ExecContext(ctx, recordProviderFailure, arg.BindingID, arg.LastError, arg.At)
	return err
}

const setBindingDesiredState = `-- name: SetBindingDesiredState :execrows
UPDATE provider_bindings
SET desired_state = ?1
WHERE id = ?2
`

type SetBindingDesiredStateParams struct {
	DesiredState string
	BindingID    int64
}

func (q *Queries) SetBindingDesiredState(ctx context.Context, arg SetBindingDesiredStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setBindingDesiredState, arg.DesiredState, arg.BindingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
