// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const backdateCacheLane = `-- name: BackdateCacheLane :execrows
UPDATE cache_lanes
SET last_used = ?1
WHERE id = ?2
`

type BackdateCacheLaneParams struct {
	LastUsed int64
	ID       string
}

func (q *Queries) BackdateCacheLane(ctx context.Context, arg BackdateCacheLaneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, backdateCacheLane, arg.LastUsed, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimCacheLane = `-- name: ClaimCacheLane :execrows
UPDATE cache_lanes
SET leased_by = ?1, last_used = unixepoch()
WHERE id = ?2 AND leased_by IS NULL
`

type ClaimCacheLaneParams struct {
	LeaseID sql.NullString
	ID      string
}

func (q *Queries) ClaimCacheLane(ctx context.Context, arg ClaimCacheLaneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimCacheLane, arg.LeaseID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countCacheLanes = `-- name: CountCacheLanes :one
SELECT count(*) FROM cache_lanes
WHERE project_id = ?1 AND generation = ?2
`

type CountCacheLanesParams struct {
	ProjectID  string
	Generation string
}

func (q *Queries) CountCacheLanes(ctx context.Context, arg CountCacheLanesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCacheLanes, arg.ProjectID, arg.Generation)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFreeCacheLane = `-- name: DeleteFreeCacheLane :execrows
DELETE FROM cache_lanes WHERE id = ?1 AND leased_by IS NULL
`

func (q *Queries) DeleteFreeCacheLane(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFreeCacheLane, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findFreeCacheLaneID = `-- name: FindFreeCacheLaneID :one
SELECT id FROM cache_lanes
WHERE project_id = ?1
  AND generation = ?2
  AND leased_by IS NULL
ORDER BY last_used DESC
LIMIT 1
`

type FindFreeCacheLaneIDParams struct {
	ProjectID  string
	Generation string
}

func (q *Queries) FindFreeCacheLaneID(ctx context.Context, arg FindFreeCacheLaneIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findFreeCacheLaneID, arg.ProjectID, arg.Generation)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getCacheProjectID = `-- name: GetCacheProjectID :one

SELECT id FROM cache_projects WHERE source_project_key = ?1
`

// Cache projects and their exclusive warm lanes.
func (q *Queries) GetCacheProjectID(ctx context.Context, sourceProjectKey string) (string, error) {
	row := q.db.QueryRowContext(ctx, getCacheProjectID, sourceProjectKey)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertCacheLane = `-- name: InsertCacheLane :exec
INSERT INTO cache_lanes (id, project_id, generation, leased_by)
VALUES (?1, ?2, ?3, ?4)
`

type InsertCacheLaneParams struct {
	ID         string
	ProjectID  string
	Generation string
	LeaseID    sql.NullString
}

func (q *Queries) InsertCacheLane(ctx context.Context, arg InsertCacheLaneParams) error {
	_, err := q.db.ExecContext(ctx, insertCacheLane,
		arg.ID,
		arg.ProjectID,
		arg.Generation,
		arg.LeaseID,
	)
	return err
}

const insertCacheProject = `-- name: InsertCacheProject :exec
INSERT INTO cache_projects (id, source_project_key)
VALUES (?1, ?2)
`

type InsertCacheProjectParams struct {
	ID               string
	SourceProjectKey string
}

func (q *Queries) InsertCacheProject(ctx context.Context, arg InsertCacheProjectParams) error {
	_, err := q.db.ExecContext(ctx, insertCacheProject, arg.ID, arg.SourceProjectKey)
	return err
}

const listCacheLanes = `-- name: ListCacheLanes :many
SELECT l.id, p.source_project_key, l.generation,
       coalesce(l.leased_by, '') AS leased_by, l.last_used
FROM cache_lanes l
JOIN cache_projects p ON p.id = l.project_id
ORDER BY p.source_project_key, l.generation, l.id
`

type ListCacheLanesRow struct {
	ID               string
	SourceProjectKey string
	Generation       string
	LeasedBy         string
	LastUsed         int64
}

func (q *Queries) ListCacheLanes(ctx context.Context) ([]ListCacheLanesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCacheLanes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCacheLanesRow{}
	for rows.Next() {
		var i ListCacheLanesRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceProjectKey,
			&i.Generation,
			&i.LeasedBy,
			&i.LastUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseCacheLane = `-- name: ReleaseCacheLane :exec
UPDATE cache_lanes SET leased_by = NULL WHERE leased_by = ?1
`

func (q *Queries) ReleaseCacheLane(ctx context.Context, leaseID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, releaseCacheLane, leaseID)
	return err
}
