// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package sqlitedb

import (
	"context"
)

const getDeliveryByKey = `-- name: GetDeliveryByKey :one
SELECT id, binding_id, source_delivery_key, payload_sha256, ack_state,
       received_at, ack_updated_at, acknowledged_at,
       payload_fingerprint_version
FROM broker_deliveries
WHERE binding_id = ?1
  AND source_delivery_key = ?2
`

type GetDeliveryByKeyParams struct {
	BindingID         int64
	SourceDeliveryKey string
}

func (q *Queries) GetDeliveryByKey(ctx context.Context, arg GetDeliveryByKeyParams) (BrokerDelivery, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryByKey, arg.BindingID, arg.SourceDeliveryKey)
	var i BrokerDelivery
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.SourceDeliveryKey,
		&i.PayloadSha256,
		&i.AckState,
		&i.ReceivedAt,
		&i.AckUpdatedAt,
		&i.AcknowledgedAt,
		&i.PayloadFingerprintVersion,
	)
	return i, err
}

const insertDelivery = `-- name: InsertDelivery :one

INSERT INTO broker_deliveries (
  binding_id, source_delivery_key, payload_sha256, payload_fingerprint_version
)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, binding_id, source_delivery_key, payload_sha256, ack_state,
          received_at, ack_updated_at, acknowledged_at,
          payload_fingerprint_version
`

type InsertDeliveryParams struct {
	BindingID                 int64
	SourceDeliveryKey         string
	PayloadSha256             []byte
	PayloadFingerprintVersion int64
}

// Broker deliveries: at-least-once messages made durable before any
// acknowledgement, with a fingerprint that tells redelivery apart from
// contract drift. Ack transitions are compare-and-swap on the states
// they may leave from; zero rows means the delivery moved and the
// caller re-reads.
func (q *Queries) InsertDelivery(ctx context.Context, arg InsertDeliveryParams) (BrokerDelivery, error) {
	row := q.db.QueryRowContext(ctx, insertDelivery,
		arg.BindingID,
		arg.SourceDeliveryKey,
		arg.PayloadSha256,
		arg.PayloadFingerprintVersion,
	)
	var i BrokerDelivery
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.SourceDeliveryKey,
		&i.PayloadSha256,
		&i.AckState,
		&i.ReceivedAt,
		&i.AckUpdatedAt,
		&i.AcknowledgedAt,
		&i.PayloadFingerprintVersion,
	)
	return i, err
}

const markAckConfirmed = `-- name: MarkAckConfirmed :execrows
UPDATE broker_deliveries
SET ack_state = 'confirmed', ack_updated_at = unixepoch(), acknowledged_at = unixepoch()
WHERE id = ?1 AND ack_state IN ('pending', 'requested', 'uncertain')
`

func (q *Queries) MarkAckConfirmed(ctx context.Context, deliveryID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAckConfirmed, deliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAckRequested = `-- name: MarkAckRequested :execrows
UPDATE broker_deliveries
SET ack_state = 'requested', ack_updated_at = unixepoch()
WHERE id = ?1 AND ack_state IN ('pending', 'requested', 'uncertain')
`

// 'requested' is included so a delivery left in flight by a crash is
// retried. The broker was never told in that state, so it redelivers the
// same message forever; excluding it made the retry a no-op and the
// binding stopped processing anything behind it in the queue.
func (q *Queries) MarkAckRequested(ctx context.Context, deliveryID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAckRequested, deliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAckUncertain = `-- name: MarkAckUncertain :execrows
UPDATE broker_deliveries
SET ack_state = 'uncertain', ack_updated_at = unixepoch()
WHERE id = ?1 AND ack_state IN ('pending', 'requested')
`

func (q *Queries) MarkAckUncertain(ctx context.Context, deliveryID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAckUncertain, deliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
