// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_actions_metadata.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const getGitHubAttemptMetadata = `-- name: GetGitHubAttemptMetadata :one
SELECT attempt_id, job_id, runner_request_id, workflow_run_id, runner_id
FROM github_actions_attempt_metadata
WHERE attempt_id = ?1
`

func (q *Queries) GetGitHubAttemptMetadata(ctx context.Context, attemptID string) (GithubActionsAttemptMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getGitHubAttemptMetadata, attemptID)
	var i GithubActionsAttemptMetadatum
	err := row.Scan(
		&i.AttemptID,
		&i.JobID,
		&i.RunnerRequestID,
		&i.WorkflowRunID,
		&i.RunnerID,
	)
	return i, err
}

const getGitHubBindingMetadata = `-- name: GetGitHubBindingMetadata :one
SELECT binding_id, scope, canonical_url, runner_group, scale_set_name, scale_set_id
FROM github_actions_binding_metadata
WHERE binding_id = ?1
`

func (q *Queries) GetGitHubBindingMetadata(ctx context.Context, bindingID int64) (GithubActionsBindingMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getGitHubBindingMetadata, bindingID)
	var i GithubActionsBindingMetadatum
	err := row.Scan(
		&i.BindingID,
		&i.Scope,
		&i.CanonicalURL,
		&i.RunnerGroup,
		&i.ScaleSetName,
		&i.ScaleSetID,
	)
	return i, err
}

const listGitHubBindingMetadata = `-- name: ListGitHubBindingMetadata :many
SELECT binding_id, scope, canonical_url, runner_group, scale_set_name, scale_set_id
FROM github_actions_binding_metadata
ORDER BY canonical_url, runner_group, scale_set_name
`

func (q *Queries) ListGitHubBindingMetadata(ctx context.Context) ([]GithubActionsBindingMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listGitHubBindingMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubActionsBindingMetadatum{}
	for rows.Next() {
		var i GithubActionsBindingMetadatum
		if err := rows.Scan(
			&i.BindingID,
			&i.Scope,
			&i.CanonicalURL,
			&i.RunnerGroup,
			&i.ScaleSetName,
			&i.ScaleSetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGitHubAttemptRunner = `-- name: SetGitHubAttemptRunner :execrows
UPDATE github_actions_attempt_metadata
SET runner_id = ?1
WHERE attempt_id = ?2
`

type SetGitHubAttemptRunnerParams struct {
	RunnerID  int64
	AttemptID string
}

// Records the ephemeral runner GitHub assigned when the capsule
// registered. It is what deregistration addresses when a capsule fails
// before GitHub expires the runner on its own.
func (q *Queries) SetGitHubAttemptRunner(ctx context.Context, arg SetGitHubAttemptRunnerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setGitHubAttemptRunner, arg.RunnerID, arg.AttemptID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertGitHubAttemptMetadata = `-- name: UpsertGitHubAttemptMetadata :exec
INSERT INTO github_actions_attempt_metadata
	(attempt_id, job_id, runner_request_id, workflow_run_id)
VALUES
	(?1, ?2, ?3, ?4)
ON CONFLICT (attempt_id) DO UPDATE SET
	job_id = excluded.job_id,
	runner_request_id = excluded.runner_request_id,
	workflow_run_id = excluded.workflow_run_id
`

type UpsertGitHubAttemptMetadataParams struct {
	AttemptID       string
	JobID           string
	RunnerRequestID int64
	WorkflowRunID   int64
}

// runner_id is deliberately absent from the conflict update: it is
// learned later, at registration, and a redelivery re-running this
// statement must not erase the id deregistration depends on.
func (q *Queries) UpsertGitHubAttemptMetadata(ctx context.Context, arg UpsertGitHubAttemptMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitHubAttemptMetadata,
		arg.AttemptID,
		arg.JobID,
		arg.RunnerRequestID,
		arg.WorkflowRunID,
	)
	return err
}

const upsertGitHubBindingMetadata = `-- name: UpsertGitHubBindingMetadata :exec

INSERT INTO github_actions_binding_metadata
	(binding_id, scope, canonical_url, runner_group, scale_set_name, scale_set_id)
VALUES
	(?1, ?2, ?3, ?4, ?5, ?6)
ON CONFLICT (binding_id) DO UPDATE SET
	scope = excluded.scope,
	canonical_url = excluded.canonical_url,
	runner_group = excluded.runner_group,
	scale_set_name = excluded.scale_set_name,
	scale_set_id = excluded.scale_set_id
`

type UpsertGitHubBindingMetadataParams struct {
	BindingID    int64
	Scope        string
	CanonicalURL string
	RunnerGroup  string
	ScaleSetName string
	ScaleSetID   sql.NullInt64
}

// GitHub Actions metadata, 1:1 with core rows and owned by the adapter.
// Diagnostic identity only: nothing here participates in the state
// machine or substitutes for the core natural keys.
func (q *Queries) UpsertGitHubBindingMetadata(ctx context.Context, arg UpsertGitHubBindingMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertGitHubBindingMetadata,
		arg.BindingID,
		arg.Scope,
		arg.CanonicalURL,
		arg.RunnerGroup,
		arg.ScaleSetName,
		arg.ScaleSetID,
	)
	return err
}
