// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leases.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const countLeasesByAttempt = `-- name: CountLeasesByAttempt :one
SELECT count(*) FROM capsule_leases WHERE attempt_id = ?1
`

func (q *Queries) CountLeasesByAttempt(ctx context.Context, attemptID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLeasesByAttempt, attemptID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrunableReleasedLeases = `-- name: CountPrunableReleasedLeases :one
SELECT count(*) FROM (
  SELECT lease.id FROM capsule_leases AS lease
  WHERE lease.state = 'released' AND lease.updated_at < ?1
    AND lease.attempt_id NOT IN (
      SELECT attempt.id FROM assignment_attempts AS attempt
      WHERE attempt.state IN ('ready', 'leased', 'preparing', 'prepared',
                      'starting', 'running', 'manual_review'))
    AND lease.id NOT IN (SELECT intent.lease_id FROM resource_intents AS intent)
  ORDER BY lease.updated_at
  LIMIT ?2
)
`

type CountPrunableReleasedLeasesParams struct {
	Before   int64
	RowLimit int64
}

func (q *Queries) CountPrunableReleasedLeases(ctx context.Context, arg CountPrunableReleasedLeasesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrunableReleasedLeases, arg.Before, arg.RowLimit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReleasedLeases = `-- name: CountReleasedLeases :one
SELECT count(*) FROM capsule_leases WHERE state = 'released'
`

func (q *Queries) CountReleasedLeases(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReleasedLeases)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAttemptIDByRuntimeName = `-- name: GetAttemptIDByRuntimeName :one
SELECT attempt_id FROM capsule_leases
WHERE runtime_name = ?1
ORDER BY rowid DESC
LIMIT 1
`

func (q *Queries) GetAttemptIDByRuntimeName(ctx context.Context, runtimeName sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, getAttemptIDByRuntimeName, runtimeName)
	var attempt_id string
	err := row.Scan(&attempt_id)
	return attempt_id, err
}

const getLease = `-- name: GetLease :one
SELECT id, binding_id, attempt_id, tier_id, state, runtime_name,
       start_observation, created_at, updated_at
FROM capsule_leases
WHERE id = ?1
`

func (q *Queries) GetLease(ctx context.Context, id string) (CapsuleLease, error) {
	row := q.db.QueryRowContext(ctx, getLease, id)
	var i CapsuleLease
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.AttemptID,
		&i.TierID,
		&i.State,
		&i.RuntimeName,
		&i.StartObservation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewestLeaseByAttempt = `-- name: GetNewestLeaseByAttempt :one
SELECT id, binding_id, attempt_id, tier_id, state, runtime_name,
       start_observation, created_at, updated_at
FROM capsule_leases
WHERE attempt_id = ?1
ORDER BY rowid DESC
LIMIT 1
`

func (q *Queries) GetNewestLeaseByAttempt(ctx context.Context, attemptID string) (CapsuleLease, error) {
	row := q.db.QueryRowContext(ctx, getNewestLeaseByAttempt, attemptID)
	var i CapsuleLease
	err := row.Scan(
		&i.ID,
		&i.BindingID,
		&i.AttemptID,
		&i.TierID,
		&i.State,
		&i.RuntimeName,
		&i.StartObservation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLease = `-- name: InsertLease :exec

INSERT INTO capsule_leases (id, binding_id, attempt_id, tier_id, state)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertLeaseParams struct {
	ID        string
	BindingID int64
	AttemptID string
	TierID    string
	State     string
}

// Capsule leases are the durable ownership record for one serving.
func (q *Queries) InsertLease(ctx context.Context, arg InsertLeaseParams) error {
	_, err := q.db.ExecContext(ctx, insertLease,
		arg.ID,
		arg.BindingID,
		arg.AttemptID,
		arg.TierID,
		arg.State,
	)
	return err
}

const listRecentReleasedLeases = `-- name: ListRecentReleasedLeases :many
SELECT id, binding_id, attempt_id, tier_id, state, runtime_name,
       start_observation, created_at, updated_at
FROM capsule_leases
WHERE state = 'released'
ORDER BY updated_at DESC, id DESC
LIMIT ?1
`

func (q *Queries) ListRecentReleasedLeases(ctx context.Context, rowLimit int64) ([]CapsuleLease, error) {
	rows, err := q.db.QueryContext(ctx, listRecentReleasedLeases, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CapsuleLease{}
	for rows.Next() {
		var i CapsuleLease
		if err := rows.Scan(
			&i.ID,
			&i.BindingID,
			&i.AttemptID,
			&i.TierID,
			&i.State,
			&i.RuntimeName,
			&i.StartObservation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneReleasedLeases = `-- name: PruneReleasedLeases :execrows
DELETE FROM capsule_leases WHERE capsule_leases.id IN (
  SELECT lease.id FROM capsule_leases AS lease
  WHERE lease.state = 'released' AND lease.updated_at < ?1
    AND lease.attempt_id NOT IN (
      SELECT attempt.id FROM assignment_attempts AS attempt
      WHERE attempt.state IN ('ready', 'leased', 'preparing', 'prepared',
                      'starting', 'running', 'manual_review'))
    AND lease.id NOT IN (SELECT intent.lease_id FROM resource_intents AS intent)
  ORDER BY lease.updated_at
  LIMIT ?2
)
`

type PruneReleasedLeasesParams struct {
	Before   int64
	RowLimit int64
}

func (q *Queries) PruneReleasedLeases(ctx context.Context, arg PruneReleasedLeasesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneReleasedLeases, arg.Before, arg.RowLimit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeResolvedLease = `-- name: PurgeResolvedLease :execrows
DELETE FROM capsule_leases
WHERE capsule_leases.id = ?1 AND capsule_leases.attempt_id NOT IN (
  SELECT attempt.id FROM assignment_attempts AS attempt
  WHERE attempt.state IN ('ready', 'leased', 'preparing', 'prepared',
                  'starting', 'running', 'manual_review')
)
`

func (q *Queries) PurgeResolvedLease(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeResolvedLease, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setLeaseRuntimeName = `-- name: SetLeaseRuntimeName :execrows
UPDATE capsule_leases
SET runtime_name = ?1, updated_at = unixepoch()
WHERE id = ?2
`

type SetLeaseRuntimeNameParams struct {
	RuntimeName sql.NullString
	ID          string
}

func (q *Queries) SetLeaseRuntimeName(ctx context.Context, arg SetLeaseRuntimeNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setLeaseRuntimeName, arg.RuntimeName, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setLeaseStartObservation = `-- name: SetLeaseStartObservation :execrows
UPDATE capsule_leases
SET start_observation = ?1, updated_at = unixepoch()
WHERE id = ?2
`

type SetLeaseStartObservationParams struct {
	StartObservation sql.NullString
	ID               string
}

func (q *Queries) SetLeaseStartObservation(ctx context.Context, arg SetLeaseStartObservationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setLeaseStartObservation, arg.StartObservation, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const transitionLease = `-- name: TransitionLease :execrows
UPDATE capsule_leases
SET state = ?1, updated_at = unixepoch()
WHERE id = ?2 AND state = ?3
`

type TransitionLeaseParams struct {
	Next    string
	ID      string
	Current string
}

func (q *Queries) TransitionLease(ctx context.Context, arg TransitionLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, transitionLease, arg.Next, arg.ID, arg.Current)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
