// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
)

type AssignmentAttempt struct {
	ID                string
	DeliveryID        int64
	BindingID         int64
	SourceWorkloadKey string
	TenantKey         string
	ProjectKey        string
	State             string
	ExecutionEvidence string
	Resolution        sql.NullString
	ReviewReason      sql.NullString
	ReviewedAt        sql.NullInt64
	ReviewedBy        sql.NullString
	ReceivedAt        int64
	SettledAt         sql.NullInt64
}

type AttemptEvent struct {
	ID             int64
	AttemptID      string
	IdempotencyKey string
	Kind           string
	DetailJson     string
	CreatedAt      int64
}

type AuditLog struct {
	ID      int64
	At      int64
	Actor   string
	Action  string
	Subject string
	Detail  string
}

type BrokerDelivery struct {
	ID                        int64
	BindingID                 int64
	SourceDeliveryKey         string
	PayloadSha256             []byte
	AckState                  string
	ReceivedAt                int64
	AckUpdatedAt              sql.NullInt64
	AcknowledgedAt            sql.NullInt64
	PayloadFingerprintVersion int64
}

type CacheLane struct {
	ID         string
	ProjectID  string
	Generation string
	LeasedBy   sql.NullString
	LastUsed   int64
}

type CacheProject struct {
	ID               string
	SourceProjectKey string
	CreatedAt        int64
}

type CapsuleLease struct {
	ID               string
	BindingID        int64
	AttemptID        string
	TierID           string
	State            string
	RuntimeName      sql.NullString
	StartObservation sql.NullString
	CreatedAt        int64
	UpdatedAt        int64
}

type GithubActionsAttemptMetadatum struct {
	AttemptID       string
	JobID           string
	RunnerRequestID int64
	WorkflowRunID   int64
	RunnerID        int64
}

type GithubActionsBindingMetadatum struct {
	BindingID    int64
	Scope        string
	CanonicalUrl string
	RunnerGroup  string
	ScaleSetName string
	ScaleSetID   sql.NullInt64
}

type Meta struct {
	K string
	V string
}

type Pressure struct {
	ID           int64
	Level        string
	FreeBytes    int64
	FreeInodes   int64
	ManagedBytes int64
	MeasuredAt   int64
}

type ProviderBinding struct {
	ID               int64
	TargetID         string
	ProviderKind     string
	SourceBindingKey string
	CreatedAt        int64
}

type ProviderBindingContact struct {
	BindingID       int64
	LastContactAtMs int64
	LastError       string
	LastErrorAtMs   int64
}

type ResourceIntent struct {
	ID        int64
	LeaseID   string
	Kind      string
	Role      string
	Name      string
	DockerID  string
	State     string
	Retries   int64
	LastError string
	NotBefore int64
	CreatedAt int64
	UpdatedAt int64
}
