// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package sqlitedb

import (
	"context"
)

const getMetaValue = `-- name: GetMetaValue :one

SELECT v FROM meta WHERE k = ?1
`

// Instance metadata and operator-facing persisted observations.
func (q *Queries) GetMetaValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetaValue, key)
	var v string
	err := row.Scan(&v)
	return v, err
}

const getPressure = `-- name: GetPressure :one
SELECT id, level, free_bytes, free_inodes, managed_bytes, measured_at
FROM pressure WHERE id = 1
`

func (q *Queries) GetPressure(ctx context.Context) (Pressure, error) {
	row := q.db.QueryRowContext(ctx, getPressure)
	var i Pressure
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.FreeBytes,
		&i.FreeInodes,
		&i.ManagedBytes,
		&i.MeasuredAt,
	)
	return i, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (actor, action, subject, detail)
VALUES (?1, ?2, ?3, ?4)
`

type InsertAuditEntryParams struct {
	Actor   string
	Action  string
	Subject string
	Detail  string
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEntry,
		arg.Actor,
		arg.Action,
		arg.Subject,
		arg.Detail,
	)
	return err
}

const listAuditTail = `-- name: ListAuditTail :many
SELECT id, at, actor, action, subject, detail
FROM audit_log
ORDER BY at DESC, id DESC
LIMIT ?1
`

func (q *Queries) ListAuditTail(ctx context.Context, rowLimit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditTail, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Actor,
			&i.Action,
			&i.Subject,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMetaValue = `-- name: UpsertMetaValue :exec
INSERT INTO meta (k, v) VALUES (?1, ?2)
ON CONFLICT (k) DO UPDATE SET v = excluded.v
`

type UpsertMetaValueParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertMetaValue(ctx context.Context, arg UpsertMetaValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertMetaValue, arg.Key, arg.Value)
	return err
}

const upsertPressure = `-- name: UpsertPressure :exec
INSERT INTO pressure (id, level, free_bytes, free_inodes, managed_bytes, measured_at)
VALUES (1, ?1, ?2, ?3, ?4, unixepoch())
ON CONFLICT (id) DO UPDATE SET
  level = excluded.level,
  free_bytes = excluded.free_bytes,
  free_inodes = excluded.free_inodes,
  managed_bytes = excluded.managed_bytes,
  measured_at = excluded.measured_at
`

type UpsertPressureParams struct {
	Level        string
	FreeBytes    int64
	FreeInodes   int64
	ManagedBytes int64
}

func (q *Queries) UpsertPressure(ctx context.Context, arg UpsertPressureParams) error {
	_, err := q.db.ExecContext(ctx, upsertPressure,
		arg.Level,
		arg.FreeBytes,
		arg.FreeInodes,
		arg.ManagedBytes,
	)
	return err
}
