// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purge.sql

package sqlitedb

import (
	"context"
)

const purgeAttemptEvents = `-- name: PurgeAttemptEvents :exec
DELETE FROM attempt_events
`

func (q *Queries) PurgeAttemptEvents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeAttemptEvents)
	return err
}

const purgeAttempts = `-- name: PurgeAttempts :exec
DELETE FROM assignment_attempts
`

func (q *Queries) PurgeAttempts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeAttempts)
	return err
}

const purgeBindings = `-- name: PurgeBindings :exec
DELETE FROM provider_bindings
`

func (q *Queries) PurgeBindings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeBindings)
	return err
}

const purgeCacheLanes = `-- name: PurgeCacheLanes :exec

DELETE FROM cache_lanes
`

// Cache lanes and their projects. Uninstall removes the lane volumes, so
// leaving the rows behind on a retained state volume strands them: every
// row keeps a leased_by pointing at a lease that no longer exists, and no
// supported path can reclaim one. Reuse needs leased_by IS NULL, GC only
// considers unleased lanes, and DeleteCacheLane refuses a leased row, so
// a reinstall would find the project already at its lane ceiling and run
// every job uncached, forever. Lanes go before projects: they reference
// them.
//
// Keep these comments ASCII. sqlc slices query text by byte offset, so a
// multi-byte character here truncates the generated SQL by as many bytes
// as it adds: an em dash in this comment produced "DELETE FROM cache_lan".
func (q *Queries) PurgeCacheLanes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeCacheLanes)
	return err
}

const purgeCacheProjects = `-- name: PurgeCacheProjects :exec
DELETE FROM cache_projects
`

func (q *Queries) PurgeCacheProjects(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeCacheProjects)
	return err
}

const purgeDeliveries = `-- name: PurgeDeliveries :exec
DELETE FROM broker_deliveries
`

func (q *Queries) PurgeDeliveries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeDeliveries)
	return err
}

const purgeGitHubAttemptMetadata = `-- name: PurgeGitHubAttemptMetadata :exec
DELETE FROM github_actions_attempt_metadata
`

func (q *Queries) PurgeGitHubAttemptMetadata(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeGitHubAttemptMetadata)
	return err
}

const purgeGitHubBindingMetadata = `-- name: PurgeGitHubBindingMetadata :exec
DELETE FROM github_actions_binding_metadata
`

func (q *Queries) PurgeGitHubBindingMetadata(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeGitHubBindingMetadata)
	return err
}

const purgeLeases = `-- name: PurgeLeases :exec
DELETE FROM capsule_leases
`

func (q *Queries) PurgeLeases(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeLeases)
	return err
}

const purgeResourceIntents = `-- name: PurgeResourceIntents :exec

DELETE FROM resource_intents
`

// Uninstall support: the operator destroying an instance takes its
// delivery and attempt evidence with it. Children before parents; each
// statement is total because uninstall names the whole instance.
//
// Order matters. Resource intents reference leases, leases reference
// attempts and bindings, attempts reference deliveries. Purging out of
// order is a foreign-key failure, which is the schema doing its job.
func (q *Queries) PurgeResourceIntents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, purgeResourceIntents)
	return err
}
