// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package sqlitedb

import (
	"context"
)

const deleteResourceIntent = `-- name: DeleteResourceIntent :execrows
DELETE FROM resource_intents WHERE id = ?1
`

func (q *Queries) DeleteResourceIntent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteResourceIntent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertResourceIntent = `-- name: InsertResourceIntent :one

INSERT INTO resource_intents (lease_id, kind, role, name)
VALUES (?1, ?2, ?3, ?4)
RETURNING id
`

type InsertResourceIntentParams struct {
	LeaseID string
	Kind    string
	Role    string
	Name    string
}

// Durable intents around external container-engine effects.
func (q *Queries) InsertResourceIntent(ctx context.Context, arg InsertResourceIntentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertResourceIntent,
		arg.LeaseID,
		arg.Kind,
		arg.Role,
		arg.Name,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listPendingResourceRemovals = `-- name: ListPendingResourceRemovals :many
SELECT id, lease_id, kind, role, name, docker_id, state, retries,
       last_error, not_before, created_at, updated_at
FROM resource_intents
WHERE state IN (?1, ?2) AND not_before <= ?3
ORDER BY not_before, id
LIMIT ?4
`

type ListPendingResourceRemovalsParams struct {
	CleanupPending string
	Deleting       string
	Now            int64
	RowLimit       int64
}

func (q *Queries) ListPendingResourceRemovals(ctx context.Context, arg ListPendingResourceRemovalsParams) ([]ResourceIntent, error) {
	rows, err := q.db.QueryContext(ctx, listPendingResourceRemovals,
		arg.CleanupPending,
		arg.Deleting,
		arg.Now,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceIntent{}
	for rows.Next() {
		var i ResourceIntent
		if err := rows.Scan(
			&i.ID,
			&i.LeaseID,
			&i.Kind,
			&i.Role,
			&i.Name,
			&i.DockerID,
			&i.State,
			&i.Retries,
			&i.LastError,
			&i.NotBefore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByLease = `-- name: ListResourcesByLease :many
SELECT id, lease_id, kind, role, name, docker_id, state, retries,
       last_error, not_before, created_at, updated_at
FROM resource_intents
WHERE lease_id = ?1
ORDER BY id
`

func (q *Queries) ListResourcesByLease(ctx context.Context, leaseID string) ([]ResourceIntent, error) {
	rows, err := q.db.QueryContext(ctx, listResourcesByLease, leaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceIntent{}
	for rows.Next() {
		var i ResourceIntent
		if err := rows.Scan(
			&i.ID,
			&i.LeaseID,
			&i.Kind,
			&i.Role,
			&i.Name,
			&i.DockerID,
			&i.State,
			&i.Retries,
			&i.LastError,
			&i.NotBefore,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markResourceCreating = `-- name: MarkResourceCreating :execrows
UPDATE resource_intents
SET state = ?1, updated_at = unixepoch()
WHERE id = ?2 AND state = ?3
`

type MarkResourceCreatingParams struct {
	Creating string
	ID       int64
	Planned  string
}

func (q *Queries) MarkResourceCreating(ctx context.Context, arg MarkResourceCreatingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markResourceCreating, arg.Creating, arg.ID, arg.Planned)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markResourceDeleting = `-- name: MarkResourceDeleting :execrows
UPDATE resource_intents
SET state = ?1, updated_at = unixepoch()
WHERE id = ?2 AND state IN (?3, ?1)
`

type MarkResourceDeletingParams struct {
	Deleting       string
	ID             int64
	CleanupPending string
}

func (q *Queries) MarkResourceDeleting(ctx context.Context, arg MarkResourceDeletingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markResourceDeleting, arg.Deleting, arg.ID, arg.CleanupPending)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markResourcePresent = `-- name: MarkResourcePresent :execrows
UPDATE resource_intents
SET state = ?1, docker_id = ?2, updated_at = unixepoch()
WHERE id = ?3 AND state IN (?4, ?5)
`

type MarkResourcePresentParams struct {
	Present  string
	DockerID string
	ID       int64
	Planned  string
	Creating string
}

func (q *Queries) MarkResourcePresent(ctx context.Context, arg MarkResourcePresentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markResourcePresent,
		arg.Present,
		arg.DockerID,
		arg.ID,
		arg.Planned,
		arg.Creating,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markResourcesForCleanup = `-- name: MarkResourcesForCleanup :exec
UPDATE resource_intents
SET state = ?1, updated_at = unixepoch()
WHERE lease_id = ?2 AND state IN (?3, ?4, ?5)
`

type MarkResourcesForCleanupParams struct {
	CleanupPending string
	LeaseID        string
	Planned        string
	Creating       string
	Present        string
}

func (q *Queries) MarkResourcesForCleanup(ctx context.Context, arg MarkResourcesForCleanupParams) error {
	_, err := q.db.ExecContext(ctx, markResourcesForCleanup,
		arg.CleanupPending,
		arg.LeaseID,
		arg.Planned,
		arg.Creating,
		arg.Present,
	)
	return err
}

const recordResourceError = `-- name: RecordResourceError :execrows
UPDATE resource_intents
SET retries = retries + 1, last_error = ?1,
    not_before = ?2, updated_at = unixepoch()
WHERE id = ?3
`

type RecordResourceErrorParams struct {
	LastError string
	NotBefore int64
	ID        int64
}

func (q *Queries) RecordResourceError(ctx context.Context, arg RecordResourceErrorParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordResourceError, arg.LastError, arg.NotBefore, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
